#!/bin/sh
echo "hello   world"
echo "hello Ringer"
echo "hello Singer"
echo "hello Pinger"
echo "hello Tinger"
echo "hello B   elle Belle"
echo "dalle dalle"
echo "Challe Challe    "
echo "TALLE       "
echo "SFDf       "
